### ISSUE TITLE
Can you provide a small sample of data

### ISSUE THREAD

**Issue by unikcc** [shrimai/Topological-Sort-for-Sentence-Ordering#1]
Thanks for your awesome work~ I have downloaded the several dataset, including NIPS, ANN, etc. But it seems that I only get the source dataset and  it doesn't match with the file named prepare_data.py. Can you show some sample of data? so that I can transfer my original data to the format and put the data to correction location like yours. Thank you!

**Comment by shrimai** [comment]
Hi, I received the AAN, NIPS and NSF data in a tar file with these three directories in it. The directory of each dataset had 3 directories - sentences, split and txt_tokenized. The split dir had 3 files names train, valid and test and they contained filenames that belonged to these splits. Both sentences and txt_tokenized had each document given in a file with the filename matching the name in its split. The document in the file is given as one sentence per line. Only the nips dataset had split file names as 2013le_papers, 2014_papers and 2015_papers. My prepare_data.py converts these into train.tsv, dev.tsv and test.tsv. The train.tsv and dev.tsv are in format: split-id \t sentence1 \t sentence2 \t label (0/1). The test.tsv is in the format: id \t sentence1 \t sentence2 \t label \t index_of_sentence1_in_document \t index_of_sentence2_in_document
Let me know if this helps.

**Comment by unikcc** [comment]
Yes it does help. Sorry for my late reply, I've started the code🚀🚀🚀. Thanks for your detailed description.

**Comment by unikcc** [comment]
> Hi, I received the AAN, NIPS and NSF data in a tar file with these three directories in it. The directory of each dataset had 3 directories - sentences, split and txt_tokenized. The split dir had 3 files names train, valid and test and they contained filenames that belonged to these splits. Both sentences and txt_tokenized had each document given in a file with the filename matching the name in its split. The document in the file is given as one sentence per line. Only the nips dataset had split file names as 2013le_papers, 2014_papers and 2015_papers. My prepare_data.py converts these into train.tsv, dev.tsv and test.tsv. The train.tsv and dev.tsv are in format: split-id \t sentence1 \t sentence2 \t label (0/1). The test.tsv is in the format: id \t sentence1 \t sentence2 \t label \t index_of_sentence1_in_document \t index_of_sentence2_in_document
> Let me know if this helps.

Yes it does help. Sorry for my late reply, I've started the code🚀🚀🚀. Thanks for your detailed description.

**Comment by shrimai** [comment]
Great. I'm closing this issue then.
